//
//  NoteCategoriesPresenter.swift
//  S.Kh_Task_25
//
//  Created by Saba Khitaridze on 23.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoteCategoriesPresentationLogic {
    func present(viewModel: NoteCategory)
    func didFailPresentCategories(withError: FileManagerError)
}

class NoteCategoriesPresenter {
    weak var viewController: NoteCategoriesDisplayLogic?
    
}

extension NoteCategoriesPresenter: NoteCategoriesPresentationLogic {
    
    func present(viewModel: NoteCategory) {
        viewController?.display(categories: viewModel.categories)
    }
    
    func didFailPresentCategories(withError: FileManagerError) {
        viewController?.didFailDisplayCategories(withError: withError)
    }
    
}
