//
//  NoteCategoriesWorker.swift
//  S.Kh_Task_25
//
//  Created by Saba Khitaridze on 23.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoteCategoriesWorkerProtocol {
    func getCategories(completion: @escaping (Result<[String], FileManagerError>) -> Void)
}

class NoteCategoriesWorker: NoteCategoriesWorkerProtocol {
    
    func getCategories(completion: @escaping (Result<[String], FileManagerError>) -> Void) {
        do {
            let allCategories = try? NoteFileManager.shared.getAllDirectories()
            guard let allCategories = allCategories else { throw FileManagerError.filePathError }
            completion(.success(allCategories))
        } catch {
            completion(.failure(FileManagerError.filePathError))
        }
    }
    
}
