//
//  NoteCategoriesRouter.swift
//  S.Kh_Task_25
//
//  Created by Saba Khitaridze on 23.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoteCategoriesRoutingLogic {
    func routeToNotes(withPath path: String)
}


class NoteCategoriesRouter {
  weak var viewController: NoteCategoriesViewController?

}


extension NoteCategoriesRouter: NoteCategoriesRoutingLogic {
    
    func routeToNotes(withPath path: String) {
        if let notesVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "NotesViewController") as? NotesViewController {
            notesVC.title = path
            NotesConfigurator.configure(vc: notesVC, path: path)
            viewController?.navigationController?.pushViewController(notesVC, animated: true)
        }
    }

}
