//
//  NotesWorker.swift
//  S.Kh_Task_25
//
//  Created by Saba Khitaridze on 24.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotesWorkerProtocol {
    func getNotes(fromDirectory directory: String, completion: @escaping (Result<[Note], FileManagerError>) -> Void)
}

class NotesWorker: NotesWorkerProtocol {
    
    func getNotes(fromDirectory directory: String, completion: @escaping (Result<[Note], FileManagerError>) -> Void) {
        do {
            let allNotes = try? NoteFileManager.shared.getAllNotes(fromDirectory: directory)
            guard let allNotes = allNotes else { throw FileManagerError.filePathError }
            completion(.success(allNotes))
        } catch {
            completion(.failure(FileManagerError.filePathError))
        }
    }
    
}
