//
//  NotesInteractor.swift
//  S.Kh_Task_25
//
//  Created by Saba Khitaridze on 24.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotesBusinessLogic {
    func fetchNotes(directory: String)
}


class NotesInteractor {
    var presenter: NotesPresentationLogic?
    var worker: NotesWorker?
    
}

extension NotesInteractor: NotesBusinessLogic {
    func fetchNotes(directory: String) {
        worker = NotesWorker()
        worker?.getNotes(fromDirectory: directory, completion: { result in
            switch result {
            case .success(let notes):
                let response = NoteModel.Response(notes: notes)
                self.presenter?.presentNotes(response: response)
            case .failure(let error):
                self.presenter?.didFailPresentNotes(withError: error)
            }
        })
    }
    
}
